name: Release WASM (GitHub Pages)
on:
  release:

env:
  PUBLIC_URL: /towerish-side-effects/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build | Trunk
        run: |
          cd launchers/wasm
          trunk build --release --public-url ${{ env.PUBLIC_URL }}

      - name: Post Build | Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: ./launchers/wasm/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Download dist
        uses: actions/download-artifact@v3
      - name: Setup | Place dist
        run: mv ./artifact ./dist
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
